import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e4e2e1",
        "secondary-fixed": "#f4e0bd",
        "on-tertiary-fixed-variant": "#485e70",
        "surface-container-low": "#f4f4f0",
        "error-container": "#fe8b70",
        "surface-tint": "#5f5e5e",
        tertiary: "#4c6174",
        "on-tertiary-container": "#3f5466",
        error: "#9e422c",
        "surface-container-high": "#e6e9e4",
        "secondary-dim": "#5f5237",
        "on-secondary-container": "#5d5035",
        "on-primary-fixed": "#3f3f3f",
        "on-tertiary-fixed": "#2c4253",
        "inverse-primary": "#ffffff",
        "error-dim": "#5c1202",
        "on-primary": "#faf7f6",
        "on-surface": "#2f3430",
        surface: "#faf9f6",
        background: "#faf9f6",
        "on-secondary-fixed-variant": "#675a3e",
        "on-secondary": "#fff8f0",
        primary: "#5f5e5e",
        "primary-container": "#e4e2e1",
        "on-primary-fixed-variant": "#5c5b5b",
        "inverse-surface": "#0d0f0d",
        "secondary-fixed-dim": "#e5d2b0",
        secondary: "#6b5d42",
        "surface-dim": "#d6dbd5",
        outline: "#777c77",
        "surface-container-highest": "#e0e4de",
        "on-error-container": "#742410",
        "tertiary-fixed-dim": "#c0d7ed",
        "tertiary-dim": "#405568",
        "on-primary-container": "#525251",
        "on-surface-variant": "#5c605c",
        "on-tertiary": "#f6f9ff",
        "inverse-on-surface": "#9d9d9a",
        "tertiary-fixed": "#cee5fb",
        "primary-dim": "#535252",
        "on-secondary-fixed": "#4a3e24",
        "surface-container": "#edeeea",
        "surface-bright": "#faf9f6",
        "surface-variant": "#e0e4de",
        "on-error": "#fff7f6",
        "outline-variant": "#afb3ae",
        "tertiary-container": "#cee5fb",
        "secondary-container": "#f4e0bd",
        "on-background": "#2f3430",
        "primary-fixed-dim": "#d6d4d3",
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
        serif: ["var(--font-newsreader)", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
